language: node_js
node_js:
- 12.16.1
addons:
  chrome: stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- npm install -g @angular/cli
script:
- npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
- npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
before_deploy:
- npm run build
- cd dist
deploy:
  - provider: cloudfoundry
    username:
      secure: XFK/gAgr4FqyNYS654NGZ0V7TIAlNmh+wvTR4mMh5R1Zm7a3QzfcxRFFhnB5ol6uzMqUU1Lf2WRfmtafwYz5lkLzSXKYYo5eHSpX/w6Rr6m4UMLyXLMK6X2aCCKcT2Bwlw5iRfQnQjHHSaBDPmrMS5n/07ECHA8AP+I+7s3fHnVapwDKxjzUwtPBNwh/biC9ErGB/8xymUNiPDOzmr8M/vBn9OoehNC3Q2Z8JzZSN21EWcyZNtykDBp5+5mQPWif2aBBoNNw0lWyzq3A6Qin+o9WzkhOsydOpy9jIxYOJOFBQHIaLVurQ8pSzZCA8xCmQHdfxFMuc0GZHGDIAbWsScMMErgqb1rhdw/OA0PYqyUM5J6temkivPKacuWEb0Btignsies5F6vkuUqWY+oegnBDDOM9FnmjjmFHhXFAM1LWVMF6xPOP/iprmYpSK2lkFymWpiIh9JxwO+F1KUPWCYjagSdXTHxsWd/abLziTbSI448jaPVZvHsOuRCCuyYC+MZKU2ksSTFVVKgUOOH3wGA7V37KMwnrCWidF8kHLFXSQh4oiKfV8W4Fmulu7hN6CEiD1zV6512K6hy5I+3QV+XyJ8G9IIVB7t2kT1GHadtyev0dGeFKLYDrqwnBFH7B+C1Bvh3VWx5BB/wyBsUtuOL0RtFWl/2vKHY35OJlpL4=
    password:
      secure: zETDDz6hLOr7fO6r5EWIV9Ep0V66lHFr/jaXyE+3UL8Sk446a5/8aMrtIqWYpRJroxZNGrfSXVScP8XMd010/GksND/hSE/Jqro4KqobtRNZuFSGze+a5TnU8CARbuSJnp6ToDmb2+wVIGRWx0he2Y6UqBDuxjbCgCmv5aH5o70bQO3cjTlFt2mCzIPCju00KX7nHYPfisgQF7cIcn8J5QSUSE96DHJPAx4aG+83bMaDy/YHbRNJ7k0wvCHmyCGjjp+xSfCoZRTJ5gmqnZKzPSa19R4jv3YpF7ji94g42HhC+ILD5hgRZ61tdcZtDsk1R5cp6mtCy+eEXDn41CmCmMAhWXiArPAS9iq1Ly9kH1zmSp9TrDNIrMTrIaI82WX1AM4TCX0YUSLyR14bM3T6GqtUNnJm0xwFuRtIq2AgclX1RVYJnh45UlxrvEdJnQE/nFGOmndb4V/xzWXhRMfQDEN9zDuZRD0pwjhBMwjGsWJrGv3v1CqFDr8YkNANOKMizlQ9U3m5euZ9qaeA8MdPb11g2WEArg09QLjJRmJLm4yXx5RH/UckiaPNci0Mx1pIhBvBDz5FwnWjHhZjou+ejhllL8ASAIllXd+53fSUoxip9/BVj7R/C/Kfwf3AWaI7Gvyp/XVgqOiPcpvvGLs7VErjemscc6dolX5f53HF27w=
    api:
      secure: jJzZRTdWqniv780ILnPygD4YByX7qXBduDYJDOlPTacVGS6nq0tINv/AediFGW0ybazDzgt/2yHeYgR6vdYQrUrSy/PdFYBURGhtGTHe8dsg8nhGNqOkbqD/OI5vi9k1WvvanHIJP8rvm6oVmYIHe6QKCi++DhjfDzAF+IcAlyx124BkFduT7KGIrAHla67icoPRwlWeq4mK2jsIxPgX501jazcjrxXNKJUl4yYvx39r8wQW3a3Y6SgxivZXYPD+c6ed6385/uXPXA5JlzDqGg9BPKrWAeexAD7IWrpESkOOZzVZw4OMHbaILkSjRBVDKY+iJAxwO5TezDMhIWzpy3O6ep/LyvHPpV06wf8qkTf8vi96ECfOOgRSmKVsL6PNOyuYUEOnYfD7IQDL1eiiPcOVWuNBLkhdqFHb7z/XQ2h8879HL44vL73EfuDs8yGUDm0Q9uKUSd64jWBgN87gUABHVPdcHlZ91C500zuxW4pPDiLRHp+PqZz7zor+y/LtkCrRmzU0UvNMVEFMgVtXRGnyZyvuUSAdIUi4mMcHayZEgRiou1p0V6uRAyet5NnhYZjOXyOm73ESs2LGRNDkOScpzHOe27pdLn3UuT7mSaAqhUaANCZQqA9BCHPw8ZalB81PgpeHQxAay+JpJGQxdBbeyp1crDCzSV/kyEEJ7Pc=
    organization:
      secure: SB+8s3M8Kptaa9zIm+jEbA8WtxLghWAPf1iYXeEHqqG2SJ3KrH0KhHo2Jx3p8R/g0qJjrLs3oIz9OBEB3PJRRs4XilPgNV4Slw5OAzROVb5OBbi/pLmVvHfa0f2DODfOWNjLmq919uojER1yk0DeDKN5ET7z0Cvzdjwq7eqcEoN4Q9SzEOLN1T8a+aiuuOXUGiOYxTNSeaVLJ1YLaXgWjrHSTE1RGsNYwUU2ZAAj/Q7FYp1BHQNS35bvr0OIv6qoUDWyaMaO9jZAyQZpCeCaZNW6o47ch7FD4SJN/gCICcGsjlMBTE2Q9tvJcRDyfMrrmsDn+yK1EqMo1RWhMfHaxFvluFQHjmIW1+HJEz/5PHCtZDLhYMXC4CzuAzv/BxjH3A1i5110FVA5AjdUnhWcMBpqY/X8vKBCnkR9mQIt1B4SpPaku0PVkAAAE+TepojxmwCwEbWhF3xDBo2aEynudLXdGflgZgGXv83oQyCUOhdWrBcRxr2ZaAoFEqjszIF8q97okSH3i5ywshUMu/RiEE/h11EOJVZcfMGmPyuU0bcYyG7D20VzOrBFHhV3T2r3w+KEQ7TVD7qEKCE+OZx5o19HRLjyOydR3TW/F0Gr9fuNZyTKRE/tbrxmB1Gj0mz6ZrqXUxi1VAa91TUZBQ1c6Jkwa5iY7e4cWJmS5Uq5xPM=
    space:
      secure: hLC6TcVHRRmEOcwP6iuRzeCK3hQxQS5ynl8JvW7q3EwjP6/gm0IeaMgvysSwKQ475ZHAx3T7qRGd2bN7XsuLtVt3CF6t9XNMDmrQJbMR7n8Hp7AaKbFZyz3q4icdeD3y49Y5RkiqJi1bDa3VrIw/X7LpBn9qgIbQopWIeasxIKfLzq21l1hzOlm3yrqnyF6ltsi85bjUr+xauirV3YLSmREucUM2xBHllYnPWtTaaQN+5+KjAEl6g9h8IHQwiMQSbEqdvqEHVyeRhYhhEY7LFqCgTeJ5LgMzmh6Xjc2t5blfWPs7mh0I2tp9xO+39nelh1RANvGUAAqfQ9ZHNWnIIKegAZ/OOdzt//p8vS/pH3NjOrt6RR47ix3VMcp9ZrC1Hwqdhyz0w7O0FB65DHtma08qZ3m9IXsY8xEX+bKgFdAbjcV2zbvvLUqVcGzz0o8APpSqYwedosAuo2W5biEB6VUQMIxzNFk1tQuUQhtXU3KsGM0liJ7fiMVdoENFWQP1tGoEVGcdYKr/LHhtnq05j9lZqa7jVoeiiG1COYfS4E/ZZ9s6Fgn4c5TZ3wna0ww/9AH2sxl66ez9MxkQH3HVuTjUTUHdBva38L19A1Fc2bBLDWLK3IWvn/jT8b6AOD4Klgein43hMal0nbqZjTvgd+uyztdAd2QFBwYNBZJ5HF0=
    manifest: "../manifest.yml"
    skip-cleanup: true
    on:
      branch: travis
